<script lang="ts">
	import { ExampleFormOutput, ExampleFormStore } from '../stores/ExampleFormStore.svelte';
	// TODO: Import your service function generated by api-integrator skill
	// Example: import { submitExample } from '$lib/{feature}/services/submitExample';
	import { formController } from '$lib/common/actions/formController.svelte';
	import Input from '$lib/common/components/Input.svelte';
	import Button from '$lib/common/components/Button.svelte';

	// Props (optional - customize based on needs)
	type Props = {
		onSuccess?: () => void;
		initialData?: { name?: string; email?: string; message?: string };
	};

	let { onSuccess, initialData }: Props = $props();

	// Create form store instance
	const formStore = new ExampleFormStore(initialData);

	// State for loading and errors
	let isLoading = $state(false);
	let errorMessage = $state('');
	let successMessage = $state('');

	// Form submission handler using neverthrow Result pattern
	async function handleSubmit(data: ExampleFormOutput) {
		isLoading = true;
		errorMessage = '';
		successMessage = '';

		// TODO: Replace with your actual service function
		// const result = await submitExample(data);
		//
		// if (result.isErr()) {
		//   errorMessage = result.error.error;
		//   isLoading = false;
		//   return;
		// }
		//
		// successMessage = 'Submitted successfully!';
		// formStore.reset();
		// onSuccess?.();
		// isLoading = false;

		// Placeholder - remove when implementing actual service call
		setTimeout(() => {
			successMessage = 'Submitted successfully!';
			formStore.reset();
			onSuccess?.();
			isLoading = false;
		}, 1000);
	}
</script>

<div class="card bg-base-100 shadow-md">
	<div class="card-body">
		<h2 class="card-title">Example Form</h2>

		{#if errorMessage}
			<div role="alert" class="alert alert-error">
				<span>{errorMessage}</span>
			</div>
		{/if}

		{#if successMessage}
			<div role="alert" class="alert alert-success">
				<span>{successMessage}</span>
			</div>
		{/if}

		<form
			class="flex flex-col gap-4"
			inert={isLoading}
			use:formController={{
				formStore,
				onSubmit: handleSubmit
			}}
		>
			<Input
				label="Name"
				name="name"
				type="text"
				placeholder="Enter your name"
				required
				error={formStore.errors.name?.message}
			/>

			<Input
				label="Email"
				name="email"
				type="email"
				placeholder="Enter your email"
				required
				error={formStore.errors.email?.message}
			/>

			<div class="flex flex-col gap-1">
				<label for="message" class="label text-sm text-gray-300">Message</label>
				<textarea
					name="message"
					id="message"
					class="textarea w-full {formStore.errors.message ? 'textarea-error' : ''}"
					placeholder="Enter your message (optional)"
					rows="4"
				></textarea>
				{#if formStore.errors.message}
					<span class="text-xs text-error">{formStore.errors.message.message}</span>
				{/if}
			</div>

			<Button type="submit" variant="primary" fullWidth loading={isLoading} class="mt-2">
				{isLoading ? 'Submitting...' : 'Submit'}
			</Button>
		</form>
	</div>
</div>
